// Hostinger Node.js entry file.
// This small app.js exists so Hostinger can detect the repository as a normal Node/Express app.
// The real TanStack Start/Nitro production server is generated by `npm run build`
// at `.output/server/index.mjs`, then started from here.

import { existsSync } from "node:fs";
import { resolve } from "node:path";
import express from "express";

const port = process.env.PORT || process.env.NITRO_PORT || 3000;
const entry = resolve(".output/server/index.mjs");

if (!existsSync(entry)) {
  const app = express();
  app.get("*", (_req, res) => {
    res.status(503).send(`
      <h1>HoorStyle app is not built yet</h1>
      <p>Run <code>npm run build</code> first, then <code>npm run start</code>.</p>
      <p>Missing file: <code>.output/server/index.mjs</code></p>
    `);
  });
  app.listen(port, () => {
    console.log(`Fallback Express server running on port ${port}`);
    console.error("Production server file not found: .output/server/index.mjs");
    console.error("Run npm run build before npm run start.");
  });
} else {
  await import(entry);
}
